### ISSUE TITLE
Make s.as lazy?

### ISSUE THREAD

**Issue by kamilkloch** [typelevel/fs2#1918]
Relates to #1909.
Why not make `as` lazy and equivalent to `_.map(_ => o2)`? By-name performace penalty?

```scala
def as[O2](o2: O2): Stream[F, O2]
```
to
```scala
def as[O2](o2: => O2): Stream[F, O2]
```

**Comment by mpilquist** [comment]
Our general position on by-name parameters is the same as used in cats -- by-names should be used sparingly and instead explicit laziness should be used. 

Some good examples of this strategy from cats:
- `map2` and `map2Eval` on `Apply` -- the latter could have been avoided by defining the second param to `map2` as a by-name parameter.
- `Semigroup` taking both arguments strictly instead of defining one or both as by-name.
- `as` on `Functor` taking its argument strictly.

So why not define these params as by-names? Some reasons:
1) It's ad-hoc -- e.g., using the semigroup example, how do we justify a choice of strict/lazy vs lazy/lazy?
2) It's not needed (much) when working in the style promoted by cats-effect and fs2 -- if evaluation should be deferred, wrap the evaluation in an effect. The only exception to this is evaluation that's deferred for stack safety (`>>`).

**Comment by kamilkloch** [comment]
Thanks for the clarification. I will stick to `map(_ => ...)` / `evalMap(_ => ...)` then. Actually, instead of the latter, we could have `evalAs[F2[x] >: F[x], O2](o2: F2[O2]): Stream[F2, O2]` ;)
