### ISSUE TITLE
.onFinalize's action doesn't run in certain situations

### ISSUE THREAD

**Issue by Yotamho** [typelevel/fs2#2497]
Hi,
Using fs2 version 2.5.9,
I am using `fs2.Stream`'s `.onFinalize`, and there are 2 operations that using them after defining the `.onFinalize` causes it to not run at all:

**case 1: calling .take(0)**
I consider it a bug especially because `.onFinalize` is usually called also on empty streams.
As a workaround I use `.drain` instead in my own code, but I assume it is less performant because it does execute all the stream even though it is not needed.

**case 2: .broadcastThrough with no pipes**
In some cases the stream doesn't need to be broadcasted at all and I would still expect the `.onFinalize` to run (I define them dynamically using `Seq` with `:_*`).
As a workaround I pass an "identity `Pipe`" whenever the Seq of pipes is empty.

link to Scastie with a demonstration of the bug: https://scastie.scala-lang.org/yotamho-cp/fDFsmsGXSeqtC3s1a1rD3A/5

**Comment by SystemFw** [comment]
> case 2: .broadcastThrough with no pipes

In 3.0, broadcasting with no pipes results in an IllegalArgumentException. 
I need to think about 1, and what the correct behaviour should be. In cats-effect, if something gets cancelled before it starts executing, finalisers don't execute either. Should `take(0)` be considered akin to that? (and therefore this behaviour is expected), or not?

**Comment by mpilquist** [comment]
How would we describe which finalizers in `s` get run in `s.take(0)`? E.g., should `s.onFinalize(f).onFinalize(g).take(0)` run both `f` and `g`? Keep in mind `s.onFinalize(f)` is an alias for `Stream.bracket(F.unit)(_ => f).flatMap(_ => s)`, so if we want to run both finalizers in that example, we need to evaluate the entire source stream to find the finalizers to run, or at least up to the first element that's been emitted, which could then be discarded. Hence, it seems like the existing behavior is correct.

**Comment by djspiewak** [comment]
It's easier if you think of `onFinalize` as being an "invisible" component of the stream, analogous to `Stream.eval_(...) ++ something`. Then, consider the semantics of `take` as being "evaluate the stream as far as necessary to get the prescribed number of `emit`s, and no further". Within this light, it makes a lot of sense that the leading `onFinalize` would be invisible.

If you *don't* do this then you end up in a lot of weird situations, like the one that @mpilquist noted above. More generally though it would mean that `s.take(0) != Stream.empty`, which *also* seems wrong and has bizarre implications. Scalaz Stream actually used this semantic for a while (finalizers were mandatory if *any* part of the stream was sequenced, even if it was `take(0)`), and we ultimately changed it because it caused these sorts of issues.

**Comment by mpilquist** [comment]
Closing this one but feel free to followup with questions, either here or in Discord, or reopen if you find some other behavior which seems wrong.
