### ISSUE TITLE
Stream.fromQueue* "losing" elements

### ISSUE THREAD

**Issue by durban** [typelevel/fs2#2723]
FS2 version: 3.2.2

I'm actually not sure this is a bug (if it's not, I'm sorry and feel free to close). Looking at the code, it's clear why this happens, but its surprising.

```scala
object test extends cats.effect.IOApp {
  import cats.Traverse
  import cats.effect.{ExitCode, IO}
  import cats.effect.std.Queue
  import fs2.Stream

  def foo = {
    for {
      q <- Queue.unbounded[IO, Option[Int]]
      _ <- Traverse[List].traverse((1 to 10).toList) { i => q.offer(Some(i)) }
      s = Stream.fromQueueNoneTerminated(q)
      r1 <- s.take(8).compile.toVector
      _ <- q.offer(None)
      r2 <- s.compile.toVector
    } yield (r1, r2)
  }

  override def run(args: List[String]): IO[ExitCode] =
    foo.flatMap(r => IO(println(r))).as(ExitCode.Success)
}
```
This program prints `(Vector(1, 2, 3, 4, 5, 6, 7, 8),Vector())`. So the items `9` and `10` are "lost".

The reason is that `Stream.fromQueue...` tries to "batch" items into a `Chunk`, then `.take(8)` gets a `Chunk` with length 10, and "loses" its last 2 items. It's understandable, but it's also strange. But I'm not sure what could be done...

**Comment by diesalbla** [comment]
@durban Thanks for opening this question or bug. However, and although I regret if you have stumbled with this, it seems to me to be working as intended.

The documentation on the `fromQueueNoneTerminated` Stream constructor states that "All elements that are available, up to the specified limit, are dequeued and emitted as a single chunk.", so your description of the operation seems accurate, but it is also following the description. 

> It's understandable, but it's also strange. But I'm not sure what could be done...

So, one thing that can be done is to use the additional `limit` parameter of the   `fromQueueNoneTerminated` method, which gives the maximum size of the chunks output by the constructed stream. Because a stream is always lazy _inter-chunks_, setting a limit of `1` means that, when pulling from the stream, it only deques one item at a time. 

I have confirmed the above. By changing the line `Stream.fromQueueNoneTerminated(q)` to 
```Scala
s = Stream.fromQueueNoneTerminated(q, 1)
```
and running it, I get the result `(Vector(1, 2, 3, 4, 5, 6, 7, 8),Vector(9, 10))`

**Comment by SystemFw** [comment]
Yeah, you can actually construct other examples of "problematic" behaviour with Queue, and they all boil down to the same thing: chunking doesn't have great fairness when multiple consumers are involved. You can actually easily engineer a deadlock with it:
```scala
  def p =
    Queue
      .unbounded[IO, Int]
      .flatMap { q =>
        1.to(10).toList.traverse(i => q.offer(i)) >>
          Stream.fromQueueUnterminated(q).take(1).compile.drain >>
          Stream.fromQueueUnterminated(q).take(1).compile.drain
      }
      .timeout(2.seconds)
      .unsafeRunSync()
```

Really the tradeoff is not avoidable, all you can do is avoid chunking when you have more than one consumer.

**Comment by durban** [comment]
Thank you, makes sense.
