### ISSUE TITLE
parEvalMapUnordered and friends can deadlock on exceptions in fs2 3.x, but not in fs2 2.x

### ISSUE THREAD

**Issue by wjoel** [typelevel/fs2#2825]
The following program gets stuck (deadlocks, never terminates) on fs2 3.2.4, but immediately finishes with an exception on fs2 2.5.10:

```scala
import cats.effect.{IO, IOApp}
import fs2.Stream

object Main extends IOApp.Simple {
  def explodeIf1(int: Int): IO[Unit] = {
    if (int == 1) {
      throw new RuntimeException("kaboom")
      // If using IO.raiseError instead, the program terminates also for fs2 3.x.
      // IO.raiseError(new RuntimeException("kaboom!"))
    } else {
      IO.unit
    }
  }

  override def run: IO[Unit] = {
    println("Hello, world!")

    val nums = 1.to(1).iterator

    Stream
      .fromIterator[IO](nums, chunkSize = 10)
      .parEvalMapUnordered[IO, Unit](2) { i =>
      explodeIf1(i)
    }.compile.drain
  }
}
```
The program also finishes (with an exception) on fs2 3.2.4 if we change `maxConcurrent` to 1, or use `IO.raiseError` instead of `throw`.

I don't think this is expected behavior, and that it should work the same as in fs2 2.x. Although we should ideally not throw, exceptions can not always be avoided.

**Comment by wjoel** [comment]
Fiber trace:
```
cats.effect.IOFiber@23e95b WAITING
 
cats.effect.IOFiber@210ab13f WAITING
 ├ get @ fs2.Stream.$anonfun$parEvalMapAction$2(Stream.scala:2142)
 ├ complete @ fs2.Stream.$anonfun$parEvalMapAction$2(Stream.scala:2142)
 ├ complete @ fs2.Stream.$anonfun$parEvalMapAction$2(Stream.scala:2142)
 ├ complete @ fs2.Stream.$anonfun$parEvalMapAction$2(Stream.scala:2142)
 ├ *> @ fs2.Stream.$anonfun$parEvalMapAction$2(Stream.scala:2115)
 ├ flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 ├ handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:160)
 ├ modify @ fs2.internal.Scope.close(Scope.scala:262)
 ├ flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 ├ flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 ╰ flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 
cats.effect.IOFiber@3535541d WAITING
 
cats.effect.IOFiber@31339bdf WAITING
 
cats.effect.IOFiber@24c22d6e WAITING
 
cats.effect.IOFiber@4e2c7e89 WAITING
 
cats.effect.IOFiber@473e4216 WAITING
 
cats.effect.IOFiber@3acd01a3 WAITING
 
cats.effect.IOFiber@54515b2a WAITING
 
cats.effect.IOFiber@636d32f7 WAITING
 
Thread[io-compute-21,5,main] (#21): 0 enqueued
Thread[io-compute-16,5,main] (#16): 0 enqueued
Thread[io-compute-19,5,main] (#19): 0 enqueued
Thread[io-compute-8,5,main] (#8): 0 enqueued
Thread[io-compute-10,5,main] (#10): 0 enqueued
Thread[io-compute-4,5,main] (#4): 0 enqueued
Thread[io-compute-17,5,main] (#17): 0 enqueued
Thread[io-compute-22,5,main] (#22): 0 enqueued
Thread[io-compute-9,5,main] (#9): 0 enqueued
Thread[io-compute-20,5,main] (#20): 0 enqueued
Thread[io-compute-6,5,main] (#6): 0 enqueued
Thread[io-compute-5,5,main] (#5): 0 enqueued
Thread[io-compute-23,5,main] (#23): 0 enqueued
Thread[io-compute-12,5,main] (#12): 0 enqueued
Thread[io-compute-3,5,main] (#3): 0 enqueued
Thread[io-compute-14,5,main] (#14): 0 enqueued
Thread[io-compute-13,5,main] (#13): 0 enqueued
Thread[io-compute-15,5,main] (#15): 0 enqueued
Thread[io-compute-18,5,main] (#18): 0 enqueued
Thread[io-compute-0,5,main] (#0): 0 enqueued
Thread[io-compute-1,5,main] (#1): 0 enqueued
Thread[io-compute-2,5,main] (#2): 0 enqueued
Thread[io-compute-7,5,main] (#7): 0 enqueued
Thread[io-compute-11,5,main] (#11): 0 enqueued
 
Global: enqueued 0, foreign 0, waiting 10
```

**Comment by armanbilge** [comment]
https://github.com/typelevel/fs2/blob/92db3c33b220cbfb11d28b850ab1cfdf0452a53c/core/shared/src/main/scala/fs2/Stream.scala#L2141-L2143

**Comment by wjoel** [comment]
A workaround (almost obvious since `IO.raiseError` works) is:
```scala
      .parEvalMapUnordered[IO, Unit](2) { i =>
        try
          explodeIf1(i)
        catch {
          case t: Throwable => IO.raiseError(t)
        }
      }
```

**Comment by armanbilge** [comment]
I think the problem is that `f(el)` throws before returning, and thus isn't caught by the `attempt`.

https://github.com/typelevel/fs2/blob/92db3c33b220cbfb11d28b850ab1cfdf0452a53c/core/shared/src/main/scala/fs2/Stream.scala#L2126-L2127

**Comment by Daenyth** [comment]
> A workaround (almost obvious since `IO.raiseError` works) is:
> 
> ```scala
>       .parEvalMapUnordered[IO, Unit](2) { i =>
>         try {
>           explodeIf1(i)
>         } catch {
>           case NonFatal(e) => IO.raiseError(e)
>         }
>       }
> ```

A more convenient way would be to do `i => IO(explodeIf1(i))`

**Comment by wjoel** [comment]
> 
> A more convenient way would be to do `i => IO(explodeIf1(i))`

I think it would have to be `IO(explodeIf(i)).flatten`, as Arman said elsewhere. In this example we return `IO.unit`, but that could have been `IO.println(int.toString)`, and we shouldn't wrap in IO twice either way.

**Comment by armanbilge** [comment]
> we shouldn't wrap in IO twice either way.

That's the thing, actually you _should_ :) In general, unless it is one of a handful of methods designated for catching thrown exceptions (off the top of my head, I think `IO(...)`, `F.delay`, `F.blocking`, `F.async`, `F.catchNonFatal`), it is not in any method's contract to automatically catch errors within the `IO`/`F`, and you can't rely on this to work. I'll echo Fabio from Discord:
> I'm not blindly about principles, and I do support, for example, the fact that `IO` catches in `map` and `flatMap` as a safety net, but I see it more as an alert for a problem you'd then need to fix by wrapping properly, rather than something you should expect to be able to actively exploit

The other thing to consider is that if we did want our code to be able to handle to thrown exceptions anywhere, this wrapping/catching does have to happen somewhere :) if we no longer assume that user-provided functions are pure (non-throwing), then library code like fs2 quickly becomes littered with `F.catchNonFatal` to try and anticipate this. 

Rather, we expect functions to be pure (which is true a large chunk of the time), and so users should wrap exception-throwing code appropriately. There's a similar expectation of the user to correctly wrap side-effects with `IO(...)` / `F.delay`, since we don't magically rewrite incorrect `F.pure(...)`.

The fact it deadlocks in this case warrants special consideration, but this would still be for "safety-net" purposes rather than correctness, so as to speak.

**Comment by wjoel** [comment]
> > we shouldn't wrap in IO twice either way.
> 
> That's the thing, actually you _should_ :)

I mean... no? This doesn't print anything (having changed the `nums` to start at `2`, so no exception), obviously, so it's not the program I want:
```scala
  def explodeIf1(int: Int): IO[Unit] =
    if (int == 1) {
      throw new RuntimeException("kaboom")
      // If using IO.raiseError instead, the program terminates also for fs2 3.x.
      // IO.raiseError(new RuntimeException("kaboom!"))
    } else {
      IO(println(int.toString))
    }

  override def run: IO[Unit] = {
    val nums = 2.to(5).iterator
    Stream
      .fromIterator[IO](nums, chunkSize = 10)
      .parEvalMapUnordered[IO, Unit](2)(i => IO(explodeIf1(i)))
      .compile
      .drain
  }
}
```

If we include `1` again, sure it catches the exception, but that's kind of missing the point, as we're now evaluating `IO(IO(...))` and just get back a pure `IO` which never gets evaluated. `i => IO(explodeIf1(i)).flatten` does work, as mentioned.

On the other hand, this program deadlocks:
```scala
  override def run: IO[Unit] = {
    val nums = 1.to(5).iterator
    Stream
      .fromIterator[IO](nums, chunkSize = 10)
      .parEvalMapUnordered[IO, Unit](2)(i => explodeIf1(i))
      .compile
      .drain
  }
```

This does not, and throws an exception instead:
```scala
  override def run: IO[Unit] = {
    val nums = 1.to(5).iterator
    Stream
      .fromIterator[IO](nums, chunkSize = 10)
      .parEvalMapUnordered[IO, Unit](1)(i => explodeIf1(i))
      .compile
      .drain
  }
```

With the only change being `2` instead of `1` for `maxConcurrent`. Getting different semantics based on the value of that parameter isn't really ok, is it? I consider that a bug, anyway.

Since https://fs2.io/#/guide?id=error-handling says exceptions are allowed. If fs2 3.x, unlike fs2 2.x, requires a different level of purity from the end user, the documentation should be updated, but honestly, the use case above seems valid enough to me, and deadlocking in the name of purity is not so valid, in my book. The workaround works for me though, so at least it's not a blocker.

**Comment by armanbilge** [comment]
Sorry, I wasn't specific enough: you should wrap _and_ flatten :) (or more generally, you should always wrap any exception-throwing code and adjust your program as necessary to preserve the semantics you want).

> Getting different semantics based on the value of that parameter isn't really ok, is it?

I would say it's "ok", because semantics are undefined anyway if you violate the contract of the method.

_However_ I wasn't aware that the docs say that. If that is intentional and not outdated, I agree that this is a bug and you are using the method correctly.

**Comment by Daenyth** [comment]
> > > we shouldn't wrap in IO twice either way.
> > 
> > 
> > That's the thing, actually you _should_ :)
> 
> I mean... no? This doesn't print anything (having changed the `nums` to start at `2`, so no exception), obviously, so it's not the program I want:

That's because it's incorrect - in fact, the compiler emits a warning about this error. Always compile with `-Ywarn-value-discard` on. This is set automatically by the sbt-tpolecat plugin, which turns on a lot of valuable lints for you, so you don't have to track which options apply to which versions of scala. But always use that warning
https://scastie.scala-lang.org/Zsx9UylTQrKuhf2MU99xxg

This is because the function you're passing to `parEvalMapUnordered` returns `IO[IO[Unit]]`; it's missing a `.flatten`
The compiler is rewriting the function to `i => { IO(explodeIf1(i)); () }` in order to satisfy the return type

It should be `IO(explodeIf1(i)).flatten`
