### ISSUE TITLE
Memory leak when a recursive stream has error handling

### ISSUE THREAD

**Issue by viewerhst** [typelevel/fs2#3404]
**Environment**
```
JDK version: 11
Scala version: 2.13.12
FS2 version: 3.9.4
```
I have a recursive function that returns `fs2.Stream`.
Inside this function, the stream does some work, and then calls the function recursively again to repeat.
In a very simplified way it looks something like this:
```scala
def infiniteStream: Stream[IO, Unit] =
  Stream
    .eval(IO(println("Do something")))
    .flatMap(_ => Stream.eval(IO(println("Next iteration"))) >> infiniteStream)

infiniteStream.compile.drain.unsafeRunSync()
```
Everything works well, but if I try to add error handling I get OutOfMemoryError error after some time:
```scala
// Leads to OutOfMemoryError
def infiniteStream: Stream[IO, Unit] =
  Stream
    .eval(IO(println("Do something")))
    .flatMap(_ => Stream.eval(IO(println("Next iteration"))) >> infiniteStream)
    .handleErrorWith(
      err => Stream.eval(IO(println(s"Exception: ${err.getMessage}"))) >> infiniteStream
    )
```
That is, it looks like there is some kind of bug with `handleErrorWith`.

**Comment by zainab-ali** [comment]
I initially thought this was a bug in `handleErrorWith`, but it boils down to scope creation.

Here's a pared down snippet with `handleErrorWith`:
https://gist.github.com/zainab-ali/03273f32e0fbbd59074e7058203623ac
```scala
def infiniteStream: Stream[IO, Unit] =
  (Stream.unit ++ infiniteStream)
    .handleErrorWith(err => Stream.unit)
```

And here's an even more concise version replacing `handleErrorWith` with the creation of a scope:
https://gist.github.com/zainab-ali/37a752320427c3081488a1c046714340
```scala
def infiniteStream: Stream[IO, Unit] =
  (Stream.unit ++ infiniteStream).pull.echo.stream // streamNoScope has no issues
```

I think recursively creating scopes would cause memory issues.

**Comment by mpilquist** [comment]
Eek! Thanks for reporting & minimizing. Can we try binary searching release versions and seeing if we can narrow it down a bit? I can try that in a couple of days if no one gets to it before me.

**Comment by mpilquist** [comment]
The issue here is that the error handlers accumulate on each recursive call. You can see the same thing happen without error handlers by having 2 consecutive `flatMap` calls instead of a `.flatMap(f).handleErrorWith(g)` like so:

```scala
  def infiniteStream: Stream[IO, Unit] =
    Stream
      .eval(IO.unit)
      .flatMap(_ => infiniteStream)
      .flatMap(_ => Stream.unit)
```

Each recursive call leaves a pending, unexecuted final `flatMap` in the continuation stack.

`IO` has the same issue:

```scala
  def run = 
    def go: IO[Unit] =
      IO.unit.flatMap(_ => go).flatMap(_ => IO.unit)
    go
```

This terminates with an OOME as well.

**Comment by armanbilge** [comment]
Conceptually we need the equivalent of the `@tailrec` annotation except for monadic recursion. The same way that you can get a stack overflow for non-tail-recursive methods, you can get an OOM for non-tail-recursive monadic programs (due to the on-heap stack growing too big, this just takes longer :)
