### ISSUE TITLE
More principled `Step` type

### ISSUE THREAD

**Issue by pchiusano** [typelevel/fs2#46]
It is sometimes useful / necessary when binding to an external API to grant control over traversing the stream to some external process. For these situations, we could use a more principled way of 'stepping' a stream, such that after each step, the caller receives the current emitted values and a next step, as well as the latest finalizer.

**Comment by florianverhein** [comment]
+1
@richardhundt that's exactly what I need too... have you had any success? (This is the closest I've come so far, but it does not handle the Task context at all...: https://gist.github.com/florianverhein/2ed965bde7324cb73325) 
There's a "toTask trick" discussed here that looks useful:  https://groups.google.com/forum/#!topic/scalaz/gx0eXHpQN48

**Comment by richardhundt** [comment]
@florianverhein I ended up with the toTask trick as well

**Comment by djspiewak** [comment]
@richardhundt @florianverhein This is interesting, because we're actually removing `toTask` in 0.7.  In theory, it would be not-horrifically-hard to implement `Process[Task, A] => Iterator[A]` on top of `step` directly (this is in fact what the new `io.toInputStream` function does in effect, though significantly obscured by some complex chunking logic).  More importantly, using `step` directly gives you the ability to close the stream if you happen to not iterate over the whole thing.  I'm not sure how relevant that is though, given that `Iterator` is `next(): A` and `hasNext(): Boolean`.  Honestly, `Iterator` is just a really bad type…

**Comment by florianverhein** [comment]
@djspiewak hmm... that's unfortunate. I tried using step, but couldn't get it to work when there was a Task context (e.g. see link earlier) - though this could be because it's a bit beyond me. toTask was much easier. I agree that Iterator isn't a great type, but there's not much choice when it's an integration issue. In my case I need a TraversableOnce, so Iterator was the simplest solution. I think it's a good idea to make it easy to drive a Process externally (i.e. suck on it till the end or close it early). The alternative (running the process and integrating via a blocking queue) is nasty.

**Comment by djspiewak** [comment]
@florianverhein There's various things we can do to try to make this situation better.  The problem of course is that if we go far enough in this direction, we just reinvent iteratees.  :-)  Perhaps a `Process[Task, A] => (Iterator[A], () => Unit)` would make sense tucked in some sort of side module somewhere.

**Comment by florianverhein** [comment]
@djspiewak yeah, that's a good idea - with the close operation optional if iteration is to the end. Brainstorm: 
- Since it's probably nicer (and closer to the way Process works) to have `def next() : Option[A]` rather than Iterator's interface, could be worth exposing that too (e.g. Iterator implementation might well be built on top of that, since it needs to read ahead to implement `hasNext()`).
- Might also be worth considering `Process1[I,O] => (Iterator[I] => Iterator[O], () => Unit)`? In particular, I have my eye on `RDD.mapPartitions` in Spark :-)

**Comment by djspiewak** [comment]
@florianverhein I think it would probably be best to move this to a new issue discussion so we have it tracked as an open feature request.  Care to do the honors?  :-)

**Comment by dcsobral** [comment]
A TraversableOnce only need implement foreach, and Process[Task, A] =>
TraversableOnce[A] is rather trivial. The whole point of TraversableOnce is
keeping control of iteration, which is the sticking point here. Alas, it
does not allow early termination.

**Comment by djspiewak** [comment]
> A TraversableOnce only need implement foreach, and `Process[Task, A] =>
TraversableOnce[A]` is rather trivial.

Actually, `Process[Task, A] => TraversableOnce[A]` is less trivial than you would think if you want to support *incremental* evaluation.  Obviously dropping down to `runLog` and throwing it all into memory is easy.  Doing things properly with `step` is slightly more complex.  Not hard, but I wouldn't classify it as "trivial".

**Comment by jedws** [comment]
OT, but I would argue that it is in fact trivial, as long as we understand
the engineer's definition of _trivial_:

http://fishbowl.pastiche.org/2007/07/17/understanding_engineers_feasibility/

cheers,
jed.

**Comment by dcsobral** [comment]
class ProcessTraversable[A](p: Process[Task, A]) extends Traversable[A] {
  def foreach[U](f: A => U): Unit = {
    val sink: Sink[Task, A] = Process.constant((x: A) => Task.delay(f(x)))
    p.to(sink).run.run
  }
}

What am I missing?

On 10 March 2015 at 22:28, Daniel Spiewak <notifications@github.com> wrote:

> A TraversableOnce only need implement foreach, and Process[Task, A] =>
> TraversableOnce[A] is rather trivial.
>
> Actually, Process[Task, A] => TraversableOnce[A] is less trivial than you
> would think if you want to support *incremental* evaluation. Obviously
> dropping down to runLog and throwing it all into memory is easy. Doing
> things properly with step is slightly more complex. Not hard, but I
> wouldn't classify it as "trivial".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/46#issuecomment-78203378>.
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by djspiewak** [comment]
@dcsobral I hadn't considered implementing it with a sink.  That works well.

**Comment by florianverhein** [comment]
@dcsobral I wish I knew scalaz well enough to understand that! ;)

**Comment by dcsobral** [comment]
It is rather trivial. Sink is a kind of Process used to produce side
effects. type Sink[M, A] = Process[M, A => M[Unit]], which looks weird but
I'll explain.

 A "normal" side effect, like any method in a very imperative Java program,
has type A => Unit. For example, going back to Java:

void println(Object o) {
  print(o);
  print("\n");
}

In other words, it takes parameters which are represented by type A. Then
it does stuff. Finally it doesn't return anything, which is represented by
type Unit.

The type of that Process is A => M[Unit] however. This simply means that
the side effect represented by "Unit" is going to be executed in the
context of the monad M, given the parameter A.

(x: A) => Task.delay(f(x))

Pretty simple, right? Given the parameter x of type A, return a Task which,
when executed, will perform f(x), where f is our side effect. The function
f could be, for example, the println method above. Let's call that function
"sideEffect". So the sink is:

Process.constant(sideEffect)

That is, it is an infinite stream of "sideEffect", where each "sideEffect"
is a function that takes an A and produces a side effect, returning
nothing. They happen to be identical because that suit our needs.

So that's our "sink". As I said at the beginning, a sink is used to perform
side effects. To give an example how, let's say we have the following two
processes:

val source: Process[Task, Int] = Process(1, 2, 3, 4, 5)
val sink: Sink[Int] = Process(f, g, h, i, j)

Then if I write "source.to(sink)", I'll get this:

Process(f(1), g(2), h(3), i(4), j(5))

And, when I run that process, I'll call the functions f, g, h, i and j with
their respective parameters.

In this case, I'm generating an infinite stream of "f", which is the
parameter to "foreach", using that with the sink, then running. That means
that if I have:

val source: Process[Task, Int] = Process(1, 2, 3, 4, 5)
val traversable = new ProcessTraversable(source)
traversable.foreach(println)

That will result in:

Process(println(1), println(2), println(3), println(4), println(5)).run.run

with the result of printing each number.

That's a Traversable -- it's a more specific type than a TraversableOnce,
in which "foreach" can only be called once.  If all you need is a
TraversableOnce, this implementation suffices.



On 11 March 2015 at 18:53, Florian Verhein <notifications@github.com> wrote:

> @dcsobral <https://github.com/dcsobral> I wish I knew scalaz well enough
> to understand that! ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/46#issuecomment-78404862>.
>



-- 
Daniel C. Sobral

I travel to the future all the time.
